name: educanexo360_app
description: Sistema de comunicación escolar EducaNexo360
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Estado y navegación
  provider: ^6.1.2
  go_router: ^14.0.0
  
  # HTTP y API
  http: ^1.2.0
  dio: ^5.4.3
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  
  # Almacenamiento local
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  
  # UI y widgets
  intl: ^0.18.1
  table_calendar: ^3.0.9
  file_picker: ^6.0.0
  url_launcher: ^6.0.0
  image_picker: ^1.0.0
  
  # Iconos
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/